name: Build PDF and Upload Artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: docker pull pandoc/extra@sha256:7e9724ee58edfa9b01af8ff4e99738f5f19a1d421e21247a23439898506d86d5

      - name: Run Make Command
        run: |
          echo $(pwd)
          make

      - name: Upload PDF Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdfs
          path: PDF/*.pdf
          if-no-files-found: error # Helpful for debugging if the build fails to produce files
          retention-days: 90       # Optional: how long to keep the files (default is 90)
